use crate::graph::Graph;
use crate::op::{ConstantValue, NodeId, Op, OpKind};
use num_complex::Complex;
use std::marker::PhantomData;
use std::ops::{Add, BitAnd, BitOr, BitXor, Div, Mul, Neg, Not, Shl, Shr, Sub};

#[derive(Clone, Copy)]
pub struct GraphValue<T> { pub(crate) node: NodeId, pub(crate) _marker: PhantomData<fn() -> T> }
impl<T> GraphValue<T> {
    pub(crate) fn from_node(node: NodeId) -> Self { Self { node, _marker: PhantomData } }
    pub(crate) fn from_op(op: Op) -> Self { Self::from_node(crate::graph::insert(op)) }
    pub(crate) fn op(&self) -> std::rc::Rc<Op> { crate::graph::get(self.node) }
    pub fn map<U,F>(self,f:F)->GraphValue<U> where F:FnOnce(GraphValue<T>)->GraphValue<U>{f(self)}
    pub fn collect(&self)->tensorflow::Graph{Graph::from_output(self.node).to_tensorflow().expect("failed to lower GraphPack graph to TensorFlow")}
    pub fn eq(&self,rhs:&GraphValue<T>)->GraphValue<bool>{binary_bool(self,rhs,OpKind::Equal)} pub fn ne(&self,rhs:&GraphValue<T>)->GraphValue<bool>{binary_bool(self,rhs,OpKind::NotEqual)} pub fn lt(&self,rhs:&GraphValue<T>)->GraphValue<bool>{binary_bool(self,rhs,OpKind::Less)} pub fn le(&self,rhs:&GraphValue<T>)->GraphValue<bool>{binary_bool(self,rhs,OpKind::LessEqual)} pub fn gt(&self,rhs:&GraphValue<T>)->GraphValue<bool>{binary_bool(self,rhs,OpKind::Greater)} pub fn ge(&self,rhs:&GraphValue<T>)->GraphValue<bool>{binary_bool(self,rhs,OpKind::GreaterEqual)}
}
impl GraphValue<bool>{pub fn and(&self,rhs:GraphValue<bool>)->GraphValue<bool>{binary(self,rhs,OpKind::LogicalAnd)} pub fn or(&self,rhs:GraphValue<bool>)->GraphValue<bool>{binary(self,rhs,OpKind::LogicalOr)} pub fn not(&self)->GraphValue<bool>{unary(self,OpKind::LogicalNot)}}
fn constant<T:IntoConstant>(value:T)->GraphValue<T>{GraphValue::from_op(Op::new(OpKind::Constant{value:value.into_constant()},vec![]))}
trait IntoConstant:Sized{fn into_constant(self)->ConstantValue;}
impl IntoConstant for f32{fn into_constant(self)->ConstantValue{ConstantValue::F32(self)}} impl IntoConstant for f64{fn into_constant(self)->ConstantValue{ConstantValue::F64(self)}} impl IntoConstant for i32{fn into_constant(self)->ConstantValue{ConstantValue::I32(self)}} impl IntoConstant for i64{fn into_constant(self)->ConstantValue{ConstantValue::I64(self)}} impl IntoConstant for usize{fn into_constant(self)->ConstantValue{ConstantValue::I64(self as i64)}} impl IntoConstant for bool{fn into_constant(self)->ConstantValue{ConstantValue::Bool(self)}} impl IntoConstant for Complex<f32>{fn into_constant(self)->ConstantValue{ConstantValue::Complex64(self)}} impl IntoConstant for Complex<f64>{fn into_constant(self)->ConstantValue{ConstantValue::Complex128(self)}} impl IntoConstant for String{fn into_constant(self)->ConstantValue{ConstantValue::String(self)}} impl IntoConstant for &str{fn into_constant(self)->ConstantValue{ConstantValue::String(self.to_owned())}}
fn binary<T>(lhs:&GraphValue<T>,rhs:GraphValue<T>,kind:OpKind)->GraphValue<T>{GraphValue::from_op(Op::new(kind,vec![lhs.node,rhs.node]))} fn binary_bool<T>(lhs:&GraphValue<T>,rhs:&GraphValue<T>,kind:OpKind)->GraphValue<bool>{GraphValue::from_op(Op::new(kind,vec![lhs.node,rhs.node]))} fn unary<T>(value:&GraphValue<T>,kind:OpKind)->GraphValue<T>{GraphValue::from_op(Op::new(kind,vec![value.node]))}
impl<T>Add for GraphValue<T>{type Output=Self;fn add(self,rhs:Self)->Self{binary(&self,rhs,OpKind::Add)}} impl<T>Sub for GraphValue<T>{type Output=Self;fn sub(self,rhs:Self)->Self{binary(&self,rhs,OpKind::Sub)}} impl<T>Mul for GraphValue<T>{type Output=Self;fn mul(self,rhs:Self)->Self{binary(&self,rhs,OpKind::Mul)}} impl<T>Div for GraphValue<T>{type Output=Self;fn div(self,rhs:Self)->Self{binary(&self,rhs,OpKind::Div)}} impl<T>Neg for GraphValue<T>{type Output=Self;fn neg(self)->Self{unary(&self,OpKind::Neg)}}
macro_rules! scalar_ops {($($t:ty),+)=>{$(impl Add<$t> for GraphValue<$t>{type Output=Self;fn add(self,rhs:$t)->Self{binary(&self,constant(rhs),OpKind::Add)}} impl Sub<$t> for GraphValue<$t>{type Output=Self;fn sub(self,rhs:$t)->Self{binary(&self,constant(rhs),OpKind::Sub)}} impl Mul<$t> for GraphValue<$t>{type Output=Self;fn mul(self,rhs:$t)->Self{binary(&self,constant(rhs),OpKind::Mul)}} impl Div<$t> for GraphValue<$t>{type Output=Self;fn div(self,rhs:$t)->Self{binary(&self,constant(rhs),OpKind::Div)}})+}} scalar_ops!(f32,f64,i32,i64,usize,Complex<f32>,Complex<f64>);
macro_rules! bits {($($t:ty),+)=>{$(impl BitAnd for GraphValue<$t>{type Output=Self;fn bitand(self,rhs:Self)->Self{binary(&self,rhs,OpKind::BitAnd)}} impl BitOr for GraphValue<$t>{type Output=Self;fn bitor(self,rhs:Self)->Self{binary(&self,rhs,OpKind::BitOr)}} impl BitXor for GraphValue<$t>{type Output=Self;fn bitxor(self,rhs:Self)->Self{binary(&self,rhs,OpKind::BitXor)}} impl Not for GraphValue<$t>{type Output=Self;fn not(self)->Self{unary(&self,OpKind::BitwiseNot)}})+}} bits!(i32,i64);
impl Shl<u32> for GraphValue<i32>{type Output=Self;fn shl(self,rhs:u32)->Self{binary(&self,constant(rhs as i32),OpKind::Shl)}} impl Shr<u32> for GraphValue<i32>{type Output=Self;fn shr(self,rhs:u32)->Self{binary(&self,constant(rhs as i32),OpKind::Shr)}} impl Shl<u32> for GraphValue<i64>{type Output=Self;fn shl(self,rhs:u32)->Self{binary(&self,constant(rhs as i64),OpKind::Shl)}} impl Shr<u32> for GraphValue<i64>{type Output=Self;fn shr(self,rhs:u32)->Self{binary(&self,constant(rhs as i64),OpKind::Shr)}}
macro_rules! scalar_cmp {($($t:ty),+)=>{$(impl GraphValue<$t>{pub fn eq_scalar(&self,rhs:$t)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::Equal)} pub fn ne_scalar(&self,rhs:$t)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::NotEqual)} pub fn lt_scalar(&self,rhs:$t)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::Less)} pub fn le_scalar(&self,rhs:$t)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::LessEqual)} pub fn gt_scalar(&self,rhs:$t)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::Greater)} pub fn ge_scalar(&self,rhs:$t)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::GreaterEqual)}})+}} scalar_cmp!(f32,f64,i32,i64,usize);
impl GraphValue<Complex<f32>>{pub fn eq_scalar(&self,rhs:Complex<f32>)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::Equal)}pub fn ne_scalar(&self,rhs:Complex<f32>)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::NotEqual)}} impl GraphValue<Complex<f64>>{pub fn eq_scalar(&self,rhs:Complex<f64>)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::Equal)}pub fn ne_scalar(&self,rhs:Complex<f64>)->GraphValue<bool>{binary_bool(self,&constant(rhs),OpKind::NotEqual)}} impl GraphValue<String>{pub fn eq_scalar(&self,rhs:&str)->GraphValue<bool>{binary_bool(self,&constant(rhs.to_string()),OpKind::Equal)}pub fn ne_scalar(&self,rhs:&str)->GraphValue<bool>{binary_bool(self,&constant(rhs.to_string()),OpKind::NotEqual)}}
