use num_complex::Complex;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub(crate) struct NodeId(pub(crate) usize);
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ScalarType { F32, F64, I8, U8, I16, U16, I32, I64, Bool, Complex64, Complex128, String }
pub trait GraphType: 'static { fn scalar_type() -> ScalarType; }
impl GraphType for f32 { fn scalar_type()->ScalarType{ScalarType::F32} } impl GraphType for f64 { fn scalar_type()->ScalarType{ScalarType::F64} } impl GraphType for i8 { fn scalar_type()->ScalarType{ScalarType::I8} } impl GraphType for u8 { fn scalar_type()->ScalarType{ScalarType::U8} } impl GraphType for i16 { fn scalar_type()->ScalarType{ScalarType::I16} } impl GraphType for u16 { fn scalar_type()->ScalarType{ScalarType::U16} } impl GraphType for i32 { fn scalar_type()->ScalarType{ScalarType::I32} } impl GraphType for i64 { fn scalar_type()->ScalarType{ScalarType::I64} } impl GraphType for usize { fn scalar_type()->ScalarType{ScalarType::I64} } impl GraphType for bool { fn scalar_type()->ScalarType{ScalarType::Bool} } impl GraphType for Complex<f32> { fn scalar_type()->ScalarType{ScalarType::Complex64} } impl GraphType for Complex<f64> { fn scalar_type()->ScalarType{ScalarType::Complex128} } impl GraphType for String { fn scalar_type()->ScalarType{ScalarType::String} }
#[derive(Clone, Debug)] pub struct Op { kind: OpKind, inputs: Vec<NodeId> }
#[derive(Clone, Debug, PartialEq)] pub enum OpKind { Input { name:String, dtype:ScalarType }, Constant { value:ConstantValue }, Map, Filter, Take { count:usize }, Skip { count:usize }, Enumerate, EnumerateIndex, Zip, ZipLeft, ZipRight, TupleGet { index: usize }, ReduceSum, ReduceProduct, ReduceMin, ReduceMax, ReduceAny, ReduceAll, ReduceCount, Fold { kind:ReduceKind }, Reduce { kind:ReduceKind }, Add, Sub, Mul, Div, Neg, BitAnd, BitOr, BitXor, BitwiseNot, Shl, Shr, Equal, NotEqual, Less, LessEqual, Greater, GreaterEqual, LogicalAnd, LogicalOr, LogicalNot }
#[derive(Clone, Copy, Debug, PartialEq, Eq)] pub enum ReduceKind { Add, Mul, Min, Max, Any, All }
#[derive(Clone, Debug, PartialEq)] pub enum ConstantValue { F32(f32), F64(f64), I8(i8), U8(u8), I16(i16), U16(u16), I32(i32), I64(i64), Bool(bool), Complex64(Complex<f32>), Complex128(Complex<f64>), String(String) }
impl ConstantValue { pub fn scalar_type(&self)->ScalarType { match self { Self::F32(_)=>ScalarType::F32, Self::F64(_)=>ScalarType::F64, Self::I8(_)=>ScalarType::I8, Self::U8(_)=>ScalarType::U8, Self::I16(_)=>ScalarType::I16, Self::U16(_)=>ScalarType::U16, Self::I32(_)=>ScalarType::I32, Self::I64(_)=>ScalarType::I64, Self::Bool(_)=>ScalarType::Bool, Self::Complex64(_)=>ScalarType::Complex64, Self::Complex128(_)=>ScalarType::Complex128, Self::String(_)=>ScalarType::String } } }
impl Op { pub(crate) fn new(kind:OpKind,inputs:Vec<NodeId>)->Self{Self{kind,inputs}} pub fn kind(&self)->&OpKind{&self.kind} pub(crate) fn inputs(&self)->&[NodeId]{&self.inputs} }
